# Cosmos REST Faucet configuration

node_home_folder = "~/.ghostcloud"
transactions_log = "transactions.csv"
request_timeout  = "43200" # Allow fetching tokens every 12 hours
cli_name         = "ghostcloudd"

[cosmos]
prefix         = "gc"
denomination   = "token"

[testnets]
    [testnets.testnet-ghostcloud-001]
    node_url       = "http://127.0.0.1:26657"
    chain_id       = "testnet-ghostcloud-001"
    faucet_address = "gc1n2usxuxjv73jgvmd7du95x6gzlnvanhr9qhhre"
    daily_cap      = "100"
    amount_to_send = "50"
    tx_fees        = "1" # TODO: Fix this with minimum fees based on gas price
